# 服务配置
server_config:
  host: "0.0.0.0"
  port: 8888

# MYSQL配置
mysql_config:
  host: "172.28.16.1"
  port: 3306
  database: "ctfe"
  username: "root"
  password: "123456"

# REDIS配置
redis_config:
  host: "172.28.16.1"
  port: 6379
  database: 0
  password: ""